version: "3.5"
services:
    passwordcockpit_backend:
        image: passwordcockpit/backend:dev
        container_name: passwordcockpit_backend
        ports:
            - "8181:80"
        volumes:
            - /path/host/volumes/backend:/var/www/html
        environment:
            PASSWORDCOCKPIT_BACKEND_DATABASE_USERNAME: passwordcockpit_db_usr
            PASSWORDCOCKPIT_BACKEND_DATABASE_PASSWORD: password
            PASSWORDCOCKPIT_BACKEND_DATABASE_HOSTNAME: 127.0.0.1:3306
            PASSWORDCOCKPIT_BACKEND_DATABASE_DATABASE: passwordcockpit
            PASSWORDCOCKPIT_BACKEND_BLOCK_CIPHER_KEY: ciphersecretkey
            PASSWORDCOCKPIT_BACKEND_AUTHENTICATION_SECRET_KEY: authenticationsecretkey
            PASSWORDCOCKPIT_BACKEND_SWAGGER_API_HOST: 127.0.0.1:8181
        depends_on:
            - passwordcockpit_database
        networks:
            - passwordcockpit_network
    passwordcockpit_frontend:
        image: passwordcockpit/frontend:dev
        container_name: passwordcockpit_frontend
        ports:
            - "8080:80"
        volumes:
            - /path/host/volumes/frontend:/var/www/html
        environment:
            PASSWORDCOCKPIT_FRONTEND_BASEHOST: http://127.0.0.1:8181
        networks:
            - passwordcockpit_network
    passwordcockpit_database:
        image: mariadb:latest
        volumes:
            - passwordcockpit_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=passwordcockpit_db_usr
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=passwordcockpit
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - "3306:3306"
        networks:
            - passwordcockpit_network
volumes:
    passwordcockpit_data:
networks:
  passwordcockpit_network:
    name: passwordcockpit_network